name: CI
on:
  push:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      # - name: SonarCloud Scan
      #   uses: SonarSource/sonarcloud-github-action@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Release
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

      - name: Trigger deployment to production
        if: github.ref == 'refs/heads/main'
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          event_type: deploy-to-prod

      - name: Trigger Deployment to Staging
        if: github.ref == 'refs/heads/develop'
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          event_type: deploy-to-staging
