name: Deploy to Staging
on:
  repository_dispatch:
    types: [deploy-to-staging]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GH_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./
          alias-domains: |
            staging.starwars.changani.me
